
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package achtml;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int cadena = 16;
  public static final int texto = 19;
  public static final int ruta = 14;
  public static final int encabezadoi = 6;
  public static final int encabezadof = 7;
  public static final int numero = 17;
  public static final int htmli = 2;
  public static final int cjsi = 8;
  public static final int cuerpoi = 4;
  public static final int ptc = 12;
  public static final int htmlf = 3;
  public static final int ccssi = 10;
  public static final int cjsf = 9;
  public static final int cuerpof = 5;
  public static final int ccssf = 11;
  public static final int titulo = 18;
  public static final int igual = 15;
  public static final int EOF = 0;
  public static final int cierre = 13;
  public static final int error = 1;
  public static final int fondo = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "htmli",
  "htmlf",
  "cuerpoi",
  "cuerpof",
  "encabezadoi",
  "encabezadof",
  "cjsi",
  "cjsf",
  "ccssi",
  "ccssf",
  "ptc",
  "cierre",
  "ruta",
  "igual",
  "cadena",
  "numero",
  "titulo",
  "texto",
  "fondo"
  };
}

