
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package cjs;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int bool = 45;
  public static final int mayory = 32;
  public static final int resta = 48;
  public static final int suma = 36;
  public static final int dimv = 2;
  public static final int imprimir = 22;
  public static final int datetime = 47;
  public static final int mayorq = 30;
  public static final int lli = 4;
  public static final int llf = 5;
  public static final int detener = 21;
  public static final int coma = 6;
  public static final int igual = 27;
  public static final int adicion = 41;
  public static final int pt = 8;
  public static final int multiplicacion = 49;
  public static final int si = 12;
  public static final int mientras = 20;
  public static final int numero = 39;
  public static final int observador = 26;
  public static final int pari = 9;
  public static final int menory = 31;
  public static final int parf = 10;
  public static final int EOF = 0;
  public static final int pyc = 7;
  public static final int menorq = 29;
  public static final int para = 19;
  public static final int error = 1;
  public static final int or = 34;
  public static final int mensaje = 14;
  public static final int funcion = 23;
  public static final int dpt = 3;
  public static final int id = 43;
  public static final int potencia = 38;
  public static final int obtener = 16;
  public static final int caso = 18;
  public static final int setelemento = 25;
  public static final int documento = 15;
  public static final int diferente = 28;
  public static final int not = 35;
  public static final int and = 33;
  public static final int atexto = 11;
  public static final int retornar = 24;
  public static final int date = 46;
  public static final int sustraccion = 42;
  public static final int division = 37;
  public static final int selecciona = 17;
  public static final int modulo = 40;
  public static final int cadena = 44;
  public static final int sino = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "dimv",
  "dpt",
  "lli",
  "llf",
  "coma",
  "pyc",
  "pt",
  "pari",
  "parf",
  "atexto",
  "si",
  "sino",
  "mensaje",
  "documento",
  "obtener",
  "selecciona",
  "caso",
  "para",
  "mientras",
  "detener",
  "imprimir",
  "funcion",
  "retornar",
  "setelemento",
  "observador",
  "igual",
  "diferente",
  "menorq",
  "mayorq",
  "menory",
  "mayory",
  "and",
  "or",
  "not",
  "suma",
  "division",
  "potencia",
  "numero",
  "modulo",
  "adicion",
  "sustraccion",
  "id",
  "cadena",
  "bool",
  "date",
  "datetime",
  "resta",
  "multiplicacion"
  };
}

