
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package ccss;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int bool = 37;
  public static final int suma = 2;
  public static final int resta = 3;
  public static final int mayuscula = 31;
  public static final int opaque = 16;
  public static final int negrilla = 29;
  public static final int asig = 20;
  public static final int coma = 21;
  public static final int derecha = 25;
  public static final int letra = 7;
  public static final int multiplicacion = 4;
  public static final int autoredimension = 11;
  public static final int grupo = 18;
  public static final int alineado = 28;
  public static final int tamtex = 8;
  public static final int numero = 38;
  public static final int justificado = 27;
  public static final int vertical = 40;
  public static final int pari = 22;
  public static final int parf = 23;
  public static final int visible = 14;
  public static final int cori = 12;
  public static final int EOF = 0;
  public static final int pyc = 10;
  public static final int corf = 13;
  public static final int error = 1;
  public static final int capital = 33;
  public static final int fondoelemento = 9;
  public static final int horizontal = 39;
  public static final int minuscula = 32;
  public static final int id = 35;
  public static final int colortext = 17;
  public static final int centrado = 26;
  public static final int texto = 6;
  public static final int izquierda = 24;
  public static final int formato = 34;
  public static final int borde = 15;
  public static final int division = 5;
  public static final int cursiva = 30;
  public static final int cadena = 36;
  public static final int ids = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "suma",
  "resta",
  "multiplicacion",
  "division",
  "texto",
  "letra",
  "tamtex",
  "fondoelemento",
  "pyc",
  "autoredimension",
  "cori",
  "corf",
  "visible",
  "borde",
  "opaque",
  "colortext",
  "grupo",
  "ids",
  "asig",
  "coma",
  "pari",
  "parf",
  "izquierda",
  "derecha",
  "centrado",
  "justificado",
  "alineado",
  "negrilla",
  "cursiva",
  "mayuscula",
  "minuscula",
  "capital",
  "formato",
  "id",
  "cadena",
  "bool",
  "numero",
  "horizontal",
  "vertical"
  };
}

