
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package chtml;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int int_ = 9;
  public static final int div = 5;
  public static final int id = 16;
  public static final int coma = 7;
  public static final int tstring = 14;
  public static final int EOF = 0;
  public static final int menos = 3;
  public static final int char_ = 12;
  public static final int numero = 13;
  public static final int puntoycoma = 6;
  public static final int double_ = 10;
  public static final int error = 1;
  public static final int string_ = 11;
  public static final int por = 4;
  public static final int mas = 2;
  public static final int tchar = 15;
  public static final int igual = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "menos",
  "por",
  "div",
  "puntoycoma",
  "coma",
  "igual",
  "int_",
  "double_",
  "string_",
  "char_",
  "numero",
  "tstring",
  "tchar",
  "id"
  };
}

